### ISSUE TITLE
Log files do not change after training

### ISSUE THREAD

**Issue by HaoyuCreate** [zacwellmer/WorldModels#12]
I am part of a group that is working on a project based off your World Models repo (as pointed to by the World Models authors). 
My group has been having troubles collecting results and visualizing them. We are simply trying to train the Car Racing model and reproduce results similar to the paper, however after three epochs of training, the log files in the results folder still appear to be your results, and not the results from our training process. 

Could you please provide any advice?

**Comment by twoletters** [comment]
Try to delete the `results` directory and start the training again using the script: `launch_scripts/carracing.bash`. It should create your own data from scratch and store them in a new `results` directory. If this doesn't work, we can look deeper into it.
