### ISSUE TITLE
Issue for training VAE

### ISSUE THREAD

**Issue by rin634** [zacwellmer/WorldModels#8]
Hello,
Thank you for the repo.  I am facing issues about training VAE(bash launch_scripts/carracing.bash) for CarRacing-v0.
1) Loss did not decreased
2) print(batch_z[0]) returns tf.Tensor([nan,nan,...,nan],shape=(32,),dtype=float32) in visualization.ipynb

I am using your Docker environments in my local Ubuntu PC.
Could you please tell me how to train correctly?

I look forward to hearing from you.
[
![Screenshot from 2021-02-24 20-59-34](https://user-images.githubusercontent.com/52065996/109000399-021e5f80-76e7-11eb-8602-299bc6386cc9.png)
](url)

**Comment by zacwellmer** [comment]
Hi @rin634 , I'm not sure what the problem is. I'd suggest to start by looking at the dataset (trajectories) collect by [extract.py](https://github.com/zacwellmer/WorldModels/blob/master/WorldModels/extract.py)
